# Generated by Django 3.1.5 on 2021-01-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
